### ISSUE TITLE
Error Variant.allDirectories when building u2020

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt-android#13]
```
  Processing manifests...*****
***** ERROR Error: com.beust.kobalt.Variant.allDirectories(Lcom/beust/kobalt/api/Project;)Ljava/util/List;
*****
java.lang.NoSuchMethodError: com.beust.kobalt.Variant.allDirectories(Lcom/beust/kobalt/api/Project;)Ljava/util/List;
	at com.beust.kobalt.plugin.android.KobaltResourceMerger$processManifests$1.invoke(KobaltResourceMerger.kt:178)
	at com.beust.kobalt.plugin.android.KobaltResourceMerger$processManifests$1.invoke(KobaltResourceMerger.kt:77)
	at com.beust.kobalt.misc.KobaltLoggerKt.logWrap(KobaltLogger.kt:31)
	at com.beust.kobalt.plugin.android.KobaltResourceMerger.processManifests(KobaltResourceMerger.kt:177)
	at com.beust.kobalt.plugin.android.KobaltResourceMerger.run(KobaltResourceMerger.kt:98)
	at com.beust.kobalt.plugin.android.AndroidPlugin.taskGenerateRFile(AndroidPlugin.kt:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.beust.kobalt.internal.TaskManager$toTaskAnnotation$1.invoke(TaskManager.kt:196)
	at com.beust.kobalt.internal.TaskManager$toTaskAnnotation$1.invoke(TaskManager.kt:18)
	at com.beust.kobalt.internal.TaskManager$addTask$1.call(TaskManager.kt:270)
	at com.beust.kobalt.internal.TaskManager$addTask$1.call(TaskManager.kt:268)
	at com.beust.kobalt.internal.ParallelProjectRunner$runProjects$ProjectTask.call(ParallelProjectRunner.kt:57)
	at com.beust.kobalt.internal.ParallelProjectRunner$runProjects$factory$1$createWorkers$result$1$1.call(ParallelProjectRunner.kt:84)
	at com.beust.kobalt.internal.ParallelProjectRunner$runProjects$factory$1$createWorkers$result$1$1.call(ParallelProjectRunner.kt:80)
	at com.beust.kobalt.internal.DynamicGraphExecutor$run2$$inlined$map$lambda$1.call(DynamicGraph.kt:227)
	at com.beust.kobalt.internal.DynamicGraphExecutor$run2$$inlined$map$lambda$1.call(DynamicGraph.kt:217)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by devvercer** [comment]
I also get this exception when building u2020
