### ISSUE TITLE
Unable launch Activty after build

### ISSUE THREAD

**Issue by fboldog** [cbeust/kobalt-android#7]
Building AnkoMaterialSamples with kobalt cause crashing apk. (same version, same settings with gradle works)
https://github.com/fboldog/AnkoMaterialSamples/

Method list diff (beetween two commits):
https://github.com/fboldog/kobalt-vs-gradle-error
(kobalt has less classes / methods)

Errors:

```
04-11 22:06:07.483  1535  1547 I ActivityManager: Start proc 2356:com.ferencboldog.ankomaterial/u0a62 for activity com.ferencboldog.ankomaterial/.launcher.LauncherActivity
04-11 22:06:07.789  2356  2356 W System  : ClassLoader referenced unknown path: /data/app/com.ferencboldog.ankomaterial-2/lib/x86_64
04-11 22:06:07.811  2356  2356 I art     : Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.app.FragmentActivity>
04-11 22:06:07.811  2356  2356 I art     : Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.app.FragmentActivity>
04-11 22:06:07.811  2356  2356 I art     : Rejecting re-init on previously-failed class java.lang.Class<android.support.v7.app.AppCompatActivity>
04-11 22:06:07.812  2356  2356 I art     : Rejecting re-init on previously-failed class java.lang.Class<android.support.v7.app.AppCompatActivity>
04-11 22:06:07.812  2356  2356 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.ferencboldog.ankomaterial.launcher.LauncherActivity>
```

```
04-11 22:06:07.874  2356  2356 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.ferencboldog.ankomaterial/com.ferencboldog.ankomaterial.launcher.LauncherActivity}: java.lang.ClassNotFoundException: Didn't find class "com.ferencboldog.ankomaterial.launcher.LauncherActivity" on path: DexPathList[[zip file "/data/app/com.ferencboldog.ankomaterial-2/base.apk"],nativeLibraryDirectories=[/data/app/com.ferencboldog.ankomaterial-2/lib/x86_64, /vendor/lib64, /system/lib64]]
04-11 22:06:07.874  2356  2356 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2327)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:    at android.app.ActivityThread.-wrap11(ActivityThread.java)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:148)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5417)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-11 22:06:07.874  2356  2356 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.ferencboldog.ankomaterial.launcher.LauncherActivity" on path: DexPathList[[zip file "/data/app/com.ferencboldog.ankomaterial-2/base.apk"],nativeLibraryDirectories=[/data/app/com.ferencboldog.ankomaterial-2/lib/x86_64, /vendor/lib64, /system/lib64]]
04-11 22:06:07.874  2356  2356 E AndroidRuntime:    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:    at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:    ... 9 more
04-11 22:06:07.874  2356  2356 E AndroidRuntime:    Suppressed: java.lang.NoClassDefFoundError: com.ferencboldog.ankomaterial.launcher.LauncherActivity
04-11 22:06:07.874  2356  2356 E AndroidRuntime:        at dalvik.system.DexFile.defineClassNative(Native Method)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:        at dalvik.system.DexFile.defineClass(DexFile.java:226)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:        at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:        at dalvik.system.DexPathList.findClass(DexPathList.java:338)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:        ... 13 more
04-11 22:06:07.874  2356  2356 E AndroidRuntime:    Suppressed: java.lang.ClassNotFoundException: com.ferencboldog.ankomaterial.launcher.LauncherActivity
04-11 22:06:07.874  2356  2356 E AndroidRuntime:        at java.lang.Class.classForName(Native Method)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-11 22:06:07.874  2356  2356 E AndroidRuntime:        ... 12 more
04-11 22:06:07.874  2356  2356 E AndroidRuntime:    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by cbeust** [comment]
Confirmed, I get the exact same stack trace.

**Comment by cbeust** [comment]
`LauncherActivity` is in the .dex and since the stack trace contains a `NoClassDefFoundException`, I think it's a dependency of that class that can't be instantiated. Bit of a misleading stack trace.

**Comment by fboldog** [comment]
[gradle-AnkoMaterialSamples-debug.apk.zip](https://github.com/cbeust/kobalt-android/files/217996/gradle-AnkoMaterialSamples-debug.apk.zip)
[gradle-build.log.zip](https://github.com/cbeust/kobalt-android/files/218003/gradle-build.log.zip)

[kobalt-AnkoMaterialSamples.apk.zip](https://github.com/cbeust/kobalt-android/files/218001/kobalt-AnkoMaterialSamples.apk.zip)
[kobalt-build.log.zip](https://github.com/cbeust/kobalt-android/files/218004/kobalt-build.log.zip)
